import * as OnboardingScreens from "./onboarding";
import * as HomeScreens from "./home";
import * as TalkScreens from "./talk";
import * as AutopilotScreens from "./autopilot";
import * as MemoryScreens from "./memory";
import * as ExecutiveScreens from "./executive";
import * as Proactive23Screens from "./proactive23";
import * as ReleaseCoreScreens from "./releaseCore";
import * as ProductionBridgeScreens from "./productionBridge";
import * as OperationalContinuityScreens from "./operationalContinuity";
import * as WorkScreens from "./work";
import * as IntakeScreens from "./intake";
import * as CustomersScreens from "./customers";
import * as SocialScreens from "./social";
import * as ResultsScreens from "./results";
import * as SettingsScreens from "./settings";

export * from "./onboarding";
export * from "./home";
export * from "./talk";
export * from "./autopilot";
export * from "./memory";
export * from "./executive";
export * from "./proactive23";
export * from "./releaseCore";
export * from "./productionBridge";
export * from "./operationalContinuity";
export * from "./work";
export * from "./intake";
export * from "./customers";
export * from "./social";
export * from "./results";
export * from "./settings";

const allScreens = {
  ...OnboardingScreens,
  ...HomeScreens,
  ...TalkScreens,
  ...AutopilotScreens,
  ...MemoryScreens,
  ...ExecutiveScreens,
  ...Proactive23Screens,
  ...ReleaseCoreScreens,
  ...ProductionBridgeScreens,
  ...OperationalContinuityScreens,
  ...WorkScreens,
  ...IntakeScreens,
  ...CustomersScreens,
  ...SocialScreens,
  ...ResultsScreens,
  ...SettingsScreens,
};

const {
  WelcomeScreen,
  SetupVertical,
  SetupBusiness,
  SetupServices,
  AddService,
  SetupLimits,
  SetupConnect,
  HomeScreen,
  ProactiveWatch,
  BackgroundWork,
  TalkToBusy,
  AutopilotCentre,
  BusinessMemory,
  ExecutiveBriefing,
  ProactiveBusyCentre,
  ReleaseCore,
  ProductionBridge,
  OperationalContinuity,
  WorkHub,
  WorkCalendar,
  WorkPipeline,
  WorkNow,
  ChooseGap,
  BestMove,
  WhyBestMove,
  ExpertBestMove,
  ProfileAudit,
  ProfileAuditPlan,
  ProfileAuditWhy,
  ExpertProfileAudit,
  OtherOptions,
  CheckSend,
  Progress,
  Replies,
  CustomerActivity,
  Bookings,
  ReplyActions,
  ReplyActionDetail,
  PaidTest,
  HowAdsWork,
  PaidRunning,
  MoreWorkGoal,
  WorkPlan,
  BusyInbox,
  AutopilotFiled,
  QuickCapture,
  QuickCaptureReview,
  QuickCaptureSaved,
  IntakeHistory,
  NewEnquiry,
  CustomerRecords,
  CustomerDetail,
  JobCompletePhotos,
  JobPhotos,
  JobPhotoOpportunity,
  PostJobBundle,
  JobPostDraft,
  JobPostApproval,
  JobPostPublished,
  JobPostOutcome,
  StaleEnquiries,
  StaleQuotes,
  EnquiryFollowUp,
  EnquiryFollowUpSent,
  EnquiryFollowUpOutcome,
  QuoteFollowUp,
  QuoteFollowUpSent,
  QuoteFollowUpOutcome,
  ReviewRequest,
  ReviewRequestSent,
  ReviewRequestOutcome,
  AddCustomerRecord,
  ConfirmRemoveCustomer,
  EligibleCustomers,
  CustomerGroups,
  BringBack,
  OfferGoal,
  OfferBuild,
  OfferPlan,
  WhyOfferPlan,
  ExpertOfferPlan,
  OfferRunning,
  SocialMediaCentre,
  SocialCreator,
  SocialDraftReview,
  OpportunityFeedback,
  BusinessBrain,
  Results,
  ResultDetails,
  UpdateOutcome,
  BusinessData,
  Settings,
  AccountAccess,
  AccountData,
  AccountRemoval,
  HowBusyWorks,
  WhatMakesDifferent,
  BusinessTypeSettings,
  CapacitySettings,
  SettingsLimits,
  RecordFilingSettings,
  ConnectedAccounts,
  Advanced
} = allScreens;

export const screens = {
  welcome: WelcomeScreen,
  setupVertical: SetupVertical,
  setupBusiness: SetupBusiness,
  setupServices: SetupServices,
  addService: AddService,
  setupLimits: SetupLimits,
  setupConnect: SetupConnect,
  home: HomeScreen,
  proactiveWatch: ProactiveWatch,
  backgroundWork: BackgroundWork,
  talkToBusy: TalkToBusy,
  autopilotCentre: AutopilotCentre,
  businessMemory: BusinessMemory,
  executiveBriefing: ExecutiveBriefing,
  proactiveBusyCentre: ProactiveBusyCentre,
  releaseCore: ReleaseCore,
  productionBridge: ProductionBridge,
  operationalContinuity: OperationalContinuity,
  workHub: WorkHub,
  workCalendar: WorkCalendar,
  workPipeline: WorkPipeline,
  workNow: WorkNow,
  chooseGap: ChooseGap,
  bestMove: BestMove,
  customerRecords: CustomerRecords,
  customerDetail: CustomerDetail,
  jobCompletePhotos: JobCompletePhotos,
  jobPhotos: JobPhotos,
  jobPhotoOpportunity: JobPhotoOpportunity,
  postJobBundle: PostJobBundle,
  jobPostDraft: JobPostDraft,
  jobPostApproval: JobPostApproval,
  jobPostPublished: JobPostPublished,
  jobPostOutcome: JobPostOutcome,
  staleEnquiries: StaleEnquiries,
  staleQuotes: StaleQuotes,
  enquiryFollowUp: EnquiryFollowUp,
  enquiryFollowUpSent: EnquiryFollowUpSent,
  enquiryFollowUpOutcome: EnquiryFollowUpOutcome,
  quoteFollowUp: QuoteFollowUp,
  quoteFollowUpSent: QuoteFollowUpSent,
  quoteFollowUpOutcome: QuoteFollowUpOutcome,
  reviewRequest: ReviewRequest,
  reviewRequestSent: ReviewRequestSent,
  reviewRequestOutcome: ReviewRequestOutcome,
  busyInbox: BusyInbox,
  autopilotFiled: AutopilotFiled,
  quickCapture: QuickCapture,
  quickCaptureReview: QuickCaptureReview,
  quickCaptureSaved: QuickCaptureSaved,
  intakeHistory: IntakeHistory,
  newEnquiry: NewEnquiry,
  addCustomerRecord: AddCustomerRecord,
  confirmRemoveCustomer: ConfirmRemoveCustomer,
  eligibleCustomers: EligibleCustomers,
  profileAudit: ProfileAudit,
  profileAuditPlan: ProfileAuditPlan,
  otherOptions: OtherOptions,
  checkSend: CheckSend,
  progress: Progress,
  replies: Replies,
  customerActivity: CustomerActivity,
  bookings: Bookings,
  replyActions: ReplyActions,
  replyActionDetail: ReplyActionDetail,
  paidTest: PaidTest,
  howAdsWork: HowAdsWork,
  paidRunning: PaidRunning,
  moreWorkGoal: MoreWorkGoal,
  workPlan: WorkPlan,
  customerGroups: CustomerGroups,
  bringBack: BringBack,
  offerGoal: OfferGoal,
  offerBuild: OfferBuild,
  offerPlan: OfferPlan,
  offerRunning: OfferRunning,
  socialMedia: SocialMediaCentre,
  socialCreator: SocialCreator,
  socialDraftReview: SocialDraftReview,
  opportunityFeedback: OpportunityFeedback,
  businessBrain: BusinessBrain,
  results: Results,
  resultDetails: ResultDetails,
  updateOutcome: UpdateOutcome,
  settings: Settings,
  businessType: BusinessTypeSettings,
  capacitySettings: CapacitySettings,
  businessData: BusinessData,
  accountData: AccountData,
  accountRemoval: AccountRemoval,
  howBusyWorks: HowBusyWorks,
  whatMakesDifferent: WhatMakesDifferent,
  settingsLimits: SettingsLimits,
  recordFilingSettings: RecordFilingSettings,
  connectedAccounts: ConnectedAccounts,
  advanced: Advanced,
};

