import { StyleSheet } from "react-native";
import { C } from "../core/runtime";

export const styles = StyleSheet.create({
  // V3.84: the Home palette now extends through every app screen and form.
  homeDarkShell: { backgroundColor: "#0D131E" },
  homeDarkContent: { paddingTop: 20, paddingBottom: 28 },
  homeDarkTopRow: { marginBottom: 17 },
  homeDarkText: { color: "#F6F9FF" },
  homeDarkHeading: { color: "#F6F9FF", fontSize: 30, lineHeight: 36 },
  homeDarkMuted: { color: "#AAB8CD" },
  homeDarkAccent: { color: "#7EDEAB" },
  homeDarkNav: { backgroundColor: "#131C2A", borderTopColor: "#344157" },
  homeDarkNavText: { color: "#9DADC5" },
  homeDarkNavActive: { color: "#8EB5FF" },
  safe: { flex: 1, backgroundColor: C.bg },
  shell: { flex: 1, backgroundColor: C.bg },
  keyboardAvoider: { flex: 1 },
  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 30 },
  scrollContentKeyboard: { paddingBottom: 220 },
  topRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 22,
  },
  brand: { fontSize: 19, fontWeight: "900", color: C.blueText, letterSpacing: 0.4 },
  busyBrandLockup: { flexDirection: "row", alignItems: "center", alignSelf: "flex-start" },
  busyBrandLockupCentered: { alignSelf: "center" },
  busyWordmarkWrap: { marginLeft: 9, justifyContent: "center" },
  busyWordmarkBusy: { color: C.ink, fontWeight: "900", letterSpacing: -0.5, lineHeight: 20 },
  busyWordmarkDoes: { color: C.blueText, fontWeight: "900", letterSpacing: 0.6, lineHeight: 16, marginTop: -1 },
  busyAssistantBase: { backgroundColor: C.blue, position: "relative", overflow: "hidden" },
  busyAssistantBackCard: { position: "absolute", backgroundColor: "#BBD8FF", transform: [{ rotate: "-8deg" }] },
  busyAssistantFrontCard: { position: "absolute", backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" },
  busyAssistantCheck: { color: C.blueText, fontWeight: "900", marginTop: 1 },
  busyAssistantLine: { backgroundColor: "#C9D4E3", borderRadius: 999, marginTop: 2 },
  busySpark: { position: "absolute", backgroundColor: C.blue, borderRadius: 999 },
  busyAppMark: { backgroundColor: C.blue, alignItems: "center", justifyContent: "center", position: "relative", overflow: "hidden" },
  busyAppMarkLetter: { color: "#FFFFFF", fontWeight: "900", letterSpacing: -2 },
  busyAppMarkCheckWrap: { position: "absolute", backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" },
  busyAppMarkCheck: { color: C.blueText, fontWeight: "900", lineHeight: 12 },
  tagline: { fontSize: 12, color: C.muted, marginTop: 4, marginLeft: 2, fontWeight: "600" },
  backPill: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: C.card,
  },
  backText: { color: C.ink, fontWeight: "700" },
  brandCue: { color: C.green, fontWeight: "800", fontSize: 15, marginBottom: 8 },
  h1: { fontSize: 29, lineHeight: 36, fontWeight: "900", color: C.ink, letterSpacing: -0.7 },
  subtitle: { fontSize: 16, lineHeight: 22, color: C.muted, marginTop: 7, marginBottom: 18 },
  card: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
    marginBottom: 12,
    backgroundColor: C.card,
  },
  cardBlue: { borderColor: "#36547B", backgroundColor: C.blueSoft },
  cardGreen: { borderColor: "#315C48", backgroundColor: C.greenSoft },
  cardAmber: { borderColor: "#735331", backgroundColor: C.amberSoft },
  eyebrow: { fontSize: 12, fontWeight: "900", color: C.blueText, letterSpacing: 0.8, marginBottom: 7 },
  busyEyebrowRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 7 },
  busyEyebrowText: { marginBottom: 0, flexShrink: 1 },
  cardTitle: { fontSize: 19, lineHeight: 25, fontWeight: "900", color: C.ink, marginBottom: 7 },
  cardBody: { fontSize: 15, lineHeight: 21, color: C.muted },
  cardFooter: { fontSize: 14, fontWeight: "900", color: C.green, marginTop: 12 },
  tick: { fontSize: 15, lineHeight: 25, color: C.ink, fontWeight: "700" },
  button: {
    minHeight: 56,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 16,
    backgroundColor: C.card,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    paddingHorizontal: 16,
  },
  buttonPrimary: { backgroundColor: C.blue, borderColor: C.blue },
  buttonDanger: { backgroundColor: C.redAction, borderColor: C.red },
  buttonDisabled: { opacity: 0.45 },
  buttonText: { fontSize: 15, fontWeight: "800", color: C.ink },
  buttonTextPrimary: { color: "#FFFFFF" },
  pressed: { transform: [{ scale: 0.99 }], opacity: 0.92 },
  smallLinkWrap: { alignItems: "center", padding: 12 },
  smallLink: { color: C.blueText, fontSize: 15, fontWeight: "700" },
  fieldWrap: { marginBottom: 15 },
  fieldLabel: { color: C.ink, fontWeight: "800", fontSize: 14, marginBottom: 7 },
  fieldBox: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.card,
    paddingHorizontal: 14,
  },
  fieldPrefix: { marginRight: 9, fontWeight: "800", color: C.muted },
  fieldInput: { flex: 1, fontSize: 16, color: C.ink, paddingVertical: 12 },
  dateFieldBox: { justifyContent: "space-between" },
  dateFieldText: { flex: 1, fontSize: 16, color: C.ink, fontWeight: "700" },
  dateFieldHint: { color: C.blueText, fontSize: 13, fontWeight: "800", marginLeft: 12 },
  datePickerPanel: { borderWidth: 1, borderColor: C.border, backgroundColor: C.card, borderRadius: 16, padding: 12, marginTop: 8, marginBottom: 14 },
  calendarHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 8 },
  calendarMonth: { color: C.ink, fontSize: 16, fontWeight: "900" },
  calendarNav: { width: 44, height: 44, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: C.blueSoft },
  calendarNavDisabled: { backgroundColor: "#273348" },
  calendarNavText: { color: C.blueText, fontSize: 30, lineHeight: 32, fontWeight: "700" },
  calendarNavTextDisabled: { color: "#9EABC0" },
  calendarGrid: { flexDirection: "row", flexWrap: "wrap" },
  calendarCell: { width: "14.2857%", alignItems: "center", justifyContent: "center", minHeight: 40 },
  calendarWeekday: { color: C.muted, fontSize: 12, fontWeight: "800" },
  calendarDay: { width: 36, height: 36, borderRadius: 18, alignItems: "center", justifyContent: "center" },
  calendarDaySelected: { backgroundColor: C.blue },
  calendarDayDisabled: { opacity: 0.28 },
  calendarDayText: { color: C.ink, fontSize: 14, fontWeight: "700" },
  calendarDayTextSelected: { color: "#FFFFFF", fontWeight: "900" },
  calendarDayTextDisabled: { color: C.muted },
  calendarHelp: { color: C.muted, fontSize: 12, textAlign: "center", marginTop: 8 },
  choice: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.card,
    borderRadius: 16,
    padding: 15,
    marginBottom: 10,
  },
  choiceSelected: { borderColor: C.blue, backgroundColor: C.blueSoft },
  radio: {
    width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: "#A2B0C7",
    alignItems: "center", justifyContent: "center", marginRight: 12,
  },
  radioSelected: { borderColor: C.blue },
  radioCore: { width: 10, height: 10, borderRadius: 5, backgroundColor: C.blue },
  choiceText: { fontSize: 16, color: C.ink, fontWeight: "800" },
  choiceTextSelected: { color: C.blueText },
  choiceSub: { marginTop: 3, color: C.muted, lineHeight: 18 },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.card,
    borderRadius: 16,
    marginBottom: 12,
  },
  toggleTitle: { fontWeight: "800", color: C.ink, fontSize: 16 },
  toggleBody: { color: C.muted, lineHeight: 19, marginTop: 4 },
  metricRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#344157",
    paddingTop: 10,
    marginTop: 10,
    gap: 14,
  },
  metricLeft: { flex: 1, minWidth: 0, color: C.muted, fontSize: 14, paddingRight: 8 },
  metricRightWrap: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 7,
    flexShrink: 1,
    maxWidth: "58%",
  },
  metricRight: {
    color: C.ink,
    fontSize: 15,
    fontWeight: "800",
    flexShrink: 1,
    textAlign: "right",
  },
  metricClickable: { color: C.blueText },
  metricChevron: { color: C.blueText, fontSize: 24, lineHeight: 24, fontWeight: "800" },
  metricRowClickable: { minHeight: 44, paddingBottom: 4 },
  metricRowPressed: { opacity: 0.58 },
  metricStrong: { fontSize: 17, fontWeight: "900", color: C.green },
  ownerIdentityBlock: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#344157",
    paddingTop: 10,
    marginTop: 10,
  },
  ownerIdentityLabel: { color: C.muted, fontSize: 14, marginBottom: 4 },
  ownerIdentityValue: {
    color: C.green,
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "900",
    flexShrink: 1,
  },
  helper: { color: C.muted, fontSize: 13, marginTop: -2, marginBottom: 14 },
  helperCenter: { color: C.muted, fontSize: 12, textAlign: "center", marginTop: 7 },
  serviceCard: {
    flexDirection: "row", alignItems: "center", borderWidth: 1, borderColor: C.border,
    backgroundColor: C.card, borderRadius: 16, padding: 16, marginBottom: 10,
  },
  serviceCardWanted: { borderColor: "#36547B", backgroundColor: C.blueSoft },
  serviceName: { fontSize: 16, fontWeight: "800", color: C.ink },
  serviceValue: { fontSize: 14, color: C.muted, marginTop: 4 },
  star: { fontSize: 28, color: "#A2B0C7" },
  starOn: { color: "#E0A419" },
  connectRow: {
    flexDirection: "row", alignItems: "center", borderWidth: 1, borderColor: C.border,
    backgroundColor: C.card, borderRadius: 16, padding: 15, marginBottom: 10, gap: 12,
  },
  connectTitle: { fontSize: 15, fontWeight: "800", color: C.ink },
  connectBody: { fontSize: 13, color: C.muted, marginTop: 3, lineHeight: 18 },
  connectButton: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 10, backgroundColor: C.blueSoft },
  connectButtonText: { fontSize: 13, fontWeight: "800", color: C.blueText },
  optionCard: {
    borderWidth: 1, borderColor: C.border, backgroundColor: C.card, borderRadius: 16,
    padding: 16, marginBottom: 10,
  },
  optionTitle: { fontSize: 17, fontWeight: "900", color: C.ink },
  optionBody: { color: C.muted, lineHeight: 20, marginTop: 5 },
  optionCost: { color: C.green, fontWeight: "900", marginTop: 9 },
  messageInput: {
    marginTop: 8, minHeight: 120, textAlignVertical: "top", color: C.ink, fontSize: 15,
    lineHeight: 21, backgroundColor: "#FFFFFFAA", borderRadius: 12, padding: 12,
    borderWidth: 1, borderColor: "#344157",
  },
  replyCard: {
    borderWidth: 1, borderColor: C.border, backgroundColor: C.card, borderRadius: 16,
    padding: 15, marginBottom: 10,
  },
  replyName: { fontWeight: "900", color: C.ink, fontSize: 16 },
  replyStatus: { color: C.green, fontWeight: "800", fontSize: 13 },
  replyStatusMuted: { color: C.muted },
  replyService: { color: C.muted, fontSize: 12, fontWeight: "700", marginTop: 2 },
  replyBody: { color: C.muted, lineHeight: 20, marginTop: 7 },
  replyActionButton: { alignSelf: "flex-start", backgroundColor: C.blue, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 10, marginTop: 12 },
  replyActionButtonText: { color: "#FFFFFF", fontWeight: "900", fontSize: 13 },
  replyActionSaved: { backgroundColor: C.greenSoft, borderRadius: 10, padding: 11, marginTop: 12 },
  replyActionSavedTitle: { color: C.green, fontWeight: "900", fontSize: 12 },
  replyActionSavedBody: { color: C.ink, fontWeight: "700", fontSize: 13, marginTop: 3 },
  replyActionSavedDetail: { color: C.muted, fontSize: 12, lineHeight: 17, marginTop: 5 },
  replyActionViewWrap: { alignSelf: "flex-start", paddingVertical: 6, marginTop: 4 },
  replyActionViewText: { color: C.blueText, fontSize: 12, fontWeight: "900" },
  replyTaskCard: { borderWidth: 1, borderColor: C.border, backgroundColor: C.card, borderRadius: 16, padding: 15, marginBottom: 10 },
  replyTaskCardDone: { opacity: 0.72 },
  replyTaskEyebrow: { color: C.blueText, fontWeight: "900", fontSize: 12, textTransform: "uppercase" },
  replyTaskName: { color: C.ink, fontWeight: "900", fontSize: 18, marginTop: 5 },
  replyTaskBody: { color: C.muted, fontSize: 14, lineHeight: 20, marginTop: 5 },
  replyTaskDoneButton: { alignSelf: "flex-start", borderRadius: 10, paddingHorizontal: 14, paddingVertical: 9, marginTop: 12, backgroundColor: C.greenSoft },
  replyTaskDoneText: { color: C.green, fontSize: 13, fontWeight: "900" },
  replyTaskOpenButton: { alignSelf: "flex-start", borderRadius: 10, paddingHorizontal: 14, paddingVertical: 10, marginTop: 12, backgroundColor: C.blue },
  replyTaskOpenText: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" },
  replyTaskDetail: { color: C.green, fontSize: 13, lineHeight: 18, fontWeight: "800", marginTop: 7 },
  replyTaskViewButton: { alignSelf: "flex-start", paddingVertical: 8, marginTop: 4 },
  replyTaskViewText: { color: C.blueText, fontSize: 13, fontWeight: "900" },
  suggestionBox: { backgroundColor: C.blueSoft, borderRadius: 14, padding: 13, marginBottom: 14 },
  suggestionTitle: { color: C.blueText, fontSize: 13, fontWeight: "900", marginBottom: 4 },
  suggestionBody: { color: C.muted, fontSize: 13, lineHeight: 19 },
  timeChoiceWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 12 },
  timeChoice: { borderWidth: 1, borderColor: C.border, backgroundColor: C.card, borderRadius: 11, paddingHorizontal: 13, paddingVertical: 10 },
  timeChoiceSelected: { backgroundColor: C.blue, borderColor: C.blue },
  timeChoiceText: { color: C.ink, fontSize: 13, fontWeight: "800" },
  timeChoiceTextSelected: { color: "#FFFFFF" },
  resultActionRow: { flexDirection: "row", alignItems: "flex-start", borderWidth: 1, borderColor: C.border, backgroundColor: C.card, borderRadius: 14, padding: 13, marginBottom: 9 },
  resultActionName: { color: C.ink, fontSize: 14, fontWeight: "900" },
  resultActionService: { color: C.muted, fontSize: 12, marginTop: 2 },
  resultActionSummary: { color: C.green, fontSize: 12, fontWeight: "800", textAlign: "right", maxWidth: "48%" },
  resultActionOpen: { color: C.blueText, fontSize: 11, fontWeight: "800", marginTop: 5 },
  activityCard: { borderWidth: 1, borderColor: C.border, backgroundColor: C.card, borderRadius: 16, padding: 15, marginBottom: 10 },
  activityCardDone: { backgroundColor: C.greenSoft, borderColor: "#315C48" },
  activityTopRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between" },
  activityName: { color: C.ink, fontSize: 17, fontWeight: "900" },
  activityService: { color: C.muted, fontSize: 13, marginTop: 2 },
  activitySummary: { color: C.ink, fontSize: 14, lineHeight: 20, fontWeight: "700", marginTop: 10 },
  activityOpen: { color: C.blueText, fontSize: 12, fontWeight: "900", marginTop: 9 },
  filterScroll: { marginBottom: 8 },
  filterRow: { flexDirection: "row", gap: 8, paddingRight: 10 },
  filterChip: { borderWidth: 1, borderColor: C.border, backgroundColor: C.card, borderRadius: 999, paddingHorizontal: 13, paddingVertical: 9 },
  filterChipActive: { backgroundColor: C.blue, borderColor: C.blue },
  filterChipText: { color: C.muted, fontSize: 12, fontWeight: "800" },
  filterChipTextActive: { color: "#FFFFFF" },
  homePriorityCard: { backgroundColor: C.greenSoft, borderWidth: 1, borderColor: "#315C48", borderRadius: 18, padding: 16, marginBottom: 16 },
  homeReminderCard: { backgroundColor: C.amberSoft, borderColor: "#735331" },
  homePriorityTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 8 },
  homePriorityEyebrow: { color: C.blueText, fontSize: 12, fontWeight: "900", letterSpacing: 0.8 },
  homePriorityTitle: { color: C.ink, fontSize: 22, fontWeight: "900" },
  homePriorityBody: { color: C.muted, fontSize: 14, lineHeight: 20, marginTop: 5 },
  homePriorityLink: { color: C.blueText, fontSize: 13, fontWeight: "900", marginTop: 10 },
  bookingCard: { borderWidth: 1, borderColor: C.border, backgroundColor: C.card, borderRadius: 16, padding: 15, marginBottom: 10 },
  bookingWhen: { color: C.ink, fontSize: 16, fontWeight: "800", marginTop: 10 },
  bookingValue: { color: C.green, fontSize: 13, fontWeight: "900", marginTop: 6 },
  suggestionBoxWarning: { backgroundColor: C.amberSoft, borderWidth: 1, borderColor: "#735331" },
  suggestionBoxSuccess: { backgroundColor: C.greenSoft, borderWidth: 1, borderColor: "#315C48" },
  clashBox: { backgroundColor: C.amberSoft, borderWidth: 1, borderColor: "#735331", borderRadius: 14, padding: 13, marginBottom: 14 },
  clashTitle: { color: C.red, fontSize: 14, fontWeight: "900", marginBottom: 4 },
  clashBody: { color: C.ink, fontSize: 13, lineHeight: 19 },
  slotFixButton: { alignSelf: "flex-start", backgroundColor: C.blue, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 9, marginTop: 10 },
  slotFixButtonText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" },
  groupCard: {
    borderWidth: 1, borderColor: C.border, backgroundColor: C.card, borderRadius: 16,
    padding: 16, marginBottom: 10,
  },
  groupCardSelected: { borderColor: C.blue, backgroundColor: C.blueSoft },
  groupTitle: { fontWeight: "900", color: C.ink, fontSize: 16, lineHeight: 21 },
  groupBody: { color: C.muted, marginTop: 6, lineHeight: 19 },
  loadingWrap: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24 },
  loadingTagline: { marginTop: 16, color: C.ink, fontSize: 16, fontWeight: "800" },
  loadingText: { marginTop: 8, color: C.muted, fontSize: 15 },
  brandShowcase: { borderRadius: 20, borderWidth: 1, borderColor: "#36547B", backgroundColor: "#1A2A44", padding: 18, marginBottom: 14 },
  brandShowcaseTitle: { color: C.ink, fontSize: 20, lineHeight: 25, fontWeight: "900", marginTop: 14 },
  brandShowcaseBody: { color: C.muted, fontSize: 14, lineHeight: 20, marginTop: 6 },
  brandCompactRow: { flexDirection: "row", alignItems: "center", gap: 12, marginTop: 16, paddingTop: 14, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: "#36547B" },
  brandCompactTitle: { color: C.ink, fontSize: 14, fontWeight: "900" },
  brandCompactBody: { color: C.muted, fontSize: 12, lineHeight: 17, marginTop: 3 },
  prototypeBadge: { marginTop: 5, alignSelf: "flex-start", fontSize: 10, fontWeight: "800", color: C.muted, backgroundColor: "#242F40", paddingHorizontal: 8, paddingVertical: 4, borderRadius: 999 },
  dashboardHeader: { marginBottom: 14 },
  dashboardHint: { color: C.muted, fontSize: 13, marginTop: 8 },
  chip: { alignSelf: "flex-start", paddingHorizontal: 9, paddingVertical: 5, borderRadius: 999 },
  chipBlue: { backgroundColor: C.blueSoft },
  chipGreen: { backgroundColor: C.greenSoft },
  chipAmber: { backgroundColor: C.amberSoft },
  chipText: { color: C.ink, fontSize: 11, fontWeight: "900" },
  opportunityCard: { borderWidth: 1, borderRadius: 18, padding: 17, marginBottom: 14, backgroundColor: C.card },
  opportunityBlue: { borderColor: "#36547B" },
  opportunityGreen: { borderColor: "#315C48" },
  opportunityAmber: { borderColor: "#735331" },
  opportunityTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 10 },
  opportunityEyebrow: { flex: 1, minWidth: 0, marginBottom: 0 },
  opportunityTitle: { fontSize: 20, lineHeight: 25, fontWeight: "900", color: C.ink, marginTop: 4 },
  opportunityBody: { color: C.muted, fontSize: 15, lineHeight: 21, marginTop: 7 },
  opportunityFooter: { color: C.green, fontSize: 14, fontWeight: "900", marginTop: 10 },
  explainWrap: { marginTop: 8 },
  inlineLinkWrap: { alignSelf: "center", paddingVertical: 9, paddingHorizontal: 6 },
  inlineLinkWrapLeft: { alignSelf: "flex-start", paddingVertical: 9, paddingHorizontal: 0 },
  inlineLink: { color: C.blueText, fontSize: 14, fontWeight: "800" },
  inlinePanel: { backgroundColor: "#FFFFFFAA", borderRadius: 12, padding: 12, borderWidth: 1, borderColor: C.border },
  inlineWhy: { color: C.ink, fontSize: 14, lineHeight: 20 },
  evidenceBox: { marginTop: 2 },
  actionRow: { flexDirection: "row", gap: 9, marginTop: 12 },
  miniPrimary: { flex: 1, minHeight: 44, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: C.blue, paddingHorizontal: 12 },
  miniPrimaryText: { color: "#FFFFFF", fontWeight: "900", fontSize: 14 },
  miniSecondary: { minHeight: 44, borderRadius: 12, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: C.border, paddingHorizontal: 15, backgroundColor: C.card },
  miniSecondaryText: { color: C.muted, fontWeight: "800", fontSize: 14 },
  progressTrack: { height: 8, borderRadius: 999, backgroundColor: "#344157", overflow: "hidden", marginTop: 10, marginBottom: 16 },
  progressFill: { height: "100%", backgroundColor: C.greenAction, borderRadius: 999 },
  warningText: { color: C.amber, fontSize: 13, lineHeight: 19, fontWeight: "700", marginTop: -2, marginBottom: 14 },
  sectionLabel: { color: C.ink, fontSize: 18, fontWeight: "900", marginTop: 8, marginBottom: 14 },
  workCalendarMonthNav: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8, marginTop: 4, marginBottom: 4 },
  workCalendarNavButton: { minHeight: 44, justifyContent: "center", paddingHorizontal: 4 },
  workCalendarNavText: { color: C.blueText, fontSize: 13, fontWeight: "900" },
  workCalendarTodayButton: { minHeight: 38, paddingHorizontal: 12, borderRadius: 12, backgroundColor: C.blueSoft, alignItems: "center", justifyContent: "center" },
  workCalendarTodayText: { color: C.blueText, fontSize: 13, fontWeight: "900" },
  workCalendarGrid: { flexDirection: "row", flexWrap: "wrap", backgroundColor: C.card, borderWidth: 1, borderColor: C.border, borderRadius: 18, paddingVertical: 8, paddingHorizontal: 4, marginBottom: 10 },
  workCalendarWeekdayCell: { width: "14.2857%", alignItems: "center", paddingVertical: 5 },
  workCalendarWeekday: { color: C.muted, fontSize: 11, fontWeight: "900" },
  workCalendarDayWrap: { width: "14.2857%", padding: 2 },
  workCalendarBlankDay: { minHeight: 54 },
  workCalendarDay: { minHeight: 54, borderRadius: 12, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "transparent", backgroundColor: "#1C2636" },
  workCalendarDaySelected: { backgroundColor: C.blueSoft, borderColor: C.blue },
  workCalendarDayToday: { borderColor: "#6B9FF7" },
  workCalendarDayPressed: { opacity: 0.58 },
  workCalendarDayNumber: { color: C.ink, fontSize: 14, fontWeight: "800" },
  workCalendarDayNumberSelected: { color: C.blueText, fontWeight: "900" },
  workCalendarMarkers: { flexDirection: "row", alignItems: "center", gap: 3, minHeight: 8, marginTop: 3 },
  workCalendarBookingDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: C.greenAction },
  workCalendarPlanDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: C.blue },
  workCalendarCount: { color: C.green, fontSize: 10, fontWeight: "900", marginTop: 1 },
  workCalendarStateText: { color: C.muted, fontSize: 8, fontWeight: "900", marginTop: 1 },
  workCalendarAttentionDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: C.amberAction },
  workCalendarExternalDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#8A94A4" },
  workCalendarAttentionCard: { flexDirection: "row", alignItems: "center", gap: 10, borderWidth: 1, borderColor: "#735331", backgroundColor: "#342817", borderRadius: 16, padding: 14, marginBottom: 9 },
  workCalendarExternalCard: { flexDirection: "row", alignItems: "center", gap: 10, borderWidth: 1, borderColor: C.border, backgroundColor: "#202C3E", borderRadius: 16, padding: 14, marginBottom: 9 },
  workCalendarLegend: { flexDirection: "row", flexWrap: "wrap", gap: 14, marginBottom: 10 },
  workCalendarLegendItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  workCalendarLegendText: { color: C.muted, fontSize: 12, fontWeight: "700" },
  workCalendarBookingCard: { flexDirection: "row", alignItems: "center", gap: 10, borderWidth: 1, borderColor: "#315C48", backgroundColor: C.greenSoft, borderRadius: 16, padding: 14, marginBottom: 9 },
  workCalendarPlanCard: { borderWidth: 1, borderColor: "#36547B", backgroundColor: C.blueSoft, borderRadius: 16, padding: 14, marginBottom: 9 },
  workCalendarBookingTitle: { color: C.ink, fontSize: 16, fontWeight: "900" },
  workCalendarBookingBody: { color: C.muted, fontSize: 13, lineHeight: 18, marginTop: 3 },
  workCalendarBookingMeta: { color: C.green, fontSize: 12, fontWeight: "900", marginTop: 5 },
  captureScreenshotGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 12 },
  captureScreenshotTile: { width: "48%", borderWidth: 1, borderColor: C.border, borderRadius: 16, padding: 8, backgroundColor: C.card },
  captureScreenshotImageWrap: { position: "relative" },
  captureScreenshotImage: { width: "100%", height: 150, borderRadius: 11, backgroundColor: "#273348" },
  captureScreenshotBadge: { position: "absolute", top: 7, left: 7, minWidth: 28, height: 28, paddingHorizontal: 8, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: C.blue },
  captureScreenshotBadgeText: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" },
  captureScreenshotName: { color: C.muted, fontSize: 11, fontWeight: "700", marginTop: 7 },
  captureScreenshotControls: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 5, marginTop: 7 },
  captureScreenshotMove: { width: 36, height: 34, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: C.blueSoft },
  captureScreenshotMoveDisabled: { opacity: 0.28 },
  captureScreenshotMoveText: { color: C.blueText, fontSize: 24, lineHeight: 26, fontWeight: "900" },
  captureScreenshotRemove: { flex: 1, minHeight: 34, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "#202C3E" },
  captureScreenshotRemoveText: { color: C.red, fontSize: 11, fontWeight: "800" },
  captureReviewStrip: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 14 },
  captureReviewThumbWrap: { position: "relative", width: 72, height: 96 },
  captureReviewThumb: { width: 72, height: 96, borderRadius: 10, backgroundColor: "#273348" },
  captureReviewBadge: { position: "absolute", top: 5, left: 5, minWidth: 22, height: 22, paddingHorizontal: 6, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: C.blue },
  captureReviewBadgeText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" },
  customerRecord: { borderWidth: 1, borderColor: C.border, backgroundColor: C.card, borderRadius: 16, padding: 15, marginBottom: 10 },
  customerRecordTop: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 8 },
  customerName: { color: C.ink, fontSize: 17, fontWeight: "900" },
  customerService: { color: C.ink, fontSize: 14, fontWeight: "800", marginTop: 8 },
  customerMeta: { color: C.muted, fontSize: 13, lineHeight: 18, marginTop: 3 },
  removeCustomerWrap: { alignSelf: "flex-start", paddingTop: 10, paddingBottom: 2 },
  removeCustomerText: { color: C.red, fontSize: 13, fontWeight: "800" },
  customerActionsRow: { flexDirection: "row", alignItems: "center", gap: 18, marginTop: 10, flexWrap: "wrap" },
  customerOpenWrap: { paddingVertical: 4, paddingRight: 4 },
  customerOpenText: { color: C.green, fontSize: 13, fontWeight: "900" },
  customerEditWrap: { paddingVertical: 4, paddingRight: 4 },
  customerEditText: { color: C.blueText, fontSize: 13, fontWeight: "900" },
  customerTimelineCard: { borderWidth: 1, borderColor: "#315C48", backgroundColor: C.greenSoft, borderRadius: 16, padding: 15, marginBottom: 14 },
  customerTimelineLabel: { color: C.blueText, fontSize: 11, fontWeight: "900", letterSpacing: 0.7, marginBottom: 5 },
  customerHistoryRow: { flexDirection: "row", alignItems: "flex-start", borderWidth: 1, borderColor: C.border, backgroundColor: C.card, borderRadius: 14, padding: 13, marginBottom: 9 },
  customerHistoryTitle: { color: C.ink, fontSize: 15, fontWeight: "900" },
  customerHistoryNote: { color: C.muted, fontSize: 12, lineHeight: 17, marginTop: 4 },
  customerHistoryValue: { color: C.green, fontSize: 15, fontWeight: "900" },
  serviceMessageCard: { borderWidth: 1, borderColor: C.border, backgroundColor: C.card, borderRadius: 16, padding: 14, marginBottom: 12 },
  serviceMessageHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 10 },
  serviceMessageTitle: { color: C.ink, fontSize: 17, fontWeight: "900" },
  serviceMessageMeta: { color: C.muted, fontSize: 13, lineHeight: 18, marginTop: 3 },
  connectButtonOn: { backgroundColor: C.greenSoft },
  photoGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 14 },
  photoTile: { width: "31%", minWidth: 96, borderRadius: 14, backgroundColor: C.card, borderWidth: 1, borderColor: C.border, overflow: "hidden" },
  photoImage: { width: "100%", aspectRatio: 1, backgroundColor: "#242F40" },
  photoRemove: { paddingVertical: 8, paddingHorizontal: 8, alignItems: "center", justifyContent: "center", backgroundColor: C.card },
  photoRemoveText: { color: C.red, fontSize: 12, fontWeight: "800" },
  customerHistoryPhotoMeta: { color: C.green, fontSize: 12, fontWeight: "800", marginTop: 7 },
  customerHistoryPhotoLink: { alignSelf: "flex-start", paddingTop: 7, paddingBottom: 2 },
  customerHistoryPhotoLinkText: { color: C.blueText, fontSize: 13, fontWeight: "800" },

  talkHomeActions: { flexDirection: "row", alignItems: "center", gap: 14, marginTop: 14, marginBottom: 12 },
  talkMicButton: { width: 64, height: 64, borderRadius: 32, backgroundColor: C.blue, alignItems: "center", justifyContent: "center" },
  talkMicButtonRecording: { backgroundColor: C.redAction },
  talkMicIcon: { fontSize: 29 },
  talkHomeCopy: { flex: 1, minWidth: 0 },
  talkHomeTitle: { color: C.ink, fontSize: 17, fontWeight: "900" },
  talkHomeBody: { color: C.muted, fontSize: 13, lineHeight: 18, marginTop: 4 },
  talkInput: { minHeight: 100, borderWidth: 1, borderColor: C.border, borderRadius: 16, backgroundColor: C.card, color: C.ink, fontSize: 16, lineHeight: 22, padding: 14, textAlignVertical: "top", marginBottom: 12 },
  talkRecordingWrap: { alignItems: "center", paddingVertical: 18 },
  talkRecordingButton: { width: 112, height: 112, borderRadius: 56, backgroundColor: C.blue, alignItems: "center", justifyContent: "center", marginBottom: 12 },
  talkRecordingButtonActive: { backgroundColor: C.redAction },
  talkRecordingIcon: { fontSize: 42 },
  talkRecordingLabel: { color: C.ink, fontSize: 17, fontWeight: "900" },
  talkRecordingTime: { color: C.muted, fontSize: 13, marginTop: 5 },
  talkHistoryCard: { borderWidth: 1, borderColor: C.border, backgroundColor: C.card, borderRadius: 14, padding: 13, marginBottom: 9 },
  talkHistoryPrompt: { color: C.ink, fontSize: 14, fontWeight: "900" },
  talkHistoryReply: { color: C.muted, fontSize: 13, lineHeight: 18, marginTop: 5 },
  operatorTurn: { borderLeftWidth: 3, borderLeftColor: C.blue, paddingLeft: 10, paddingVertical: 7, marginBottom: 8 },
  operatorTurnRole: { color: C.blueText, fontSize: 10, fontWeight: "900", letterSpacing: 0.8 },
  operatorTurnText: { color: C.ink, fontSize: 14, lineHeight: 19, marginTop: 3 },
  operatorDraft: { borderWidth: 1, borderColor: "#36547B", backgroundColor: C.blueSoft, borderRadius: 14, padding: 14, marginTop: 12, marginBottom: 12 },
  operatorDraftLabel: { color: C.blueText, fontSize: 10, fontWeight: "900", letterSpacing: 0.8 },
  operatorDraftText: { color: C.ink, fontSize: 15, lineHeight: 21, marginTop: 7 },
  operatorDraftHint: { color: C.muted, fontSize: 12, lineHeight: 17, marginTop: 9 },
  operatorPlanWrap: { marginTop: 12 },
  operatorPlanStep: { flexDirection: "row", gap: 10, borderWidth: 1, borderColor: C.border, backgroundColor: C.card, borderRadius: 14, padding: 12, marginBottom: 10 },
  operatorPlanNumber: { width: 30, height: 30, borderRadius: 15, backgroundColor: C.blue, alignItems: "center", justifyContent: "center" },
  operatorPlanNumberText: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" },
  operatorPlanTitle: { color: C.ink, fontSize: 15, fontWeight: "900" },
  operatorPlanReason: { color: C.muted, fontSize: 13, lineHeight: 18, marginTop: 4 },
  operatorPlanSafety: { color: C.amber, fontSize: 11, fontWeight: "800", marginTop: 5 },
  autopilotRuleInput: { minHeight: 92, borderWidth: 1, borderColor: C.border, borderRadius: 14, backgroundColor: C.card, color: C.ink, fontSize: 15, lineHeight: 21, padding: 13, textAlignVertical: "top", marginTop: 10, marginBottom: 10 },
  autopilotRuleExamples: { color: C.muted, fontSize: 12, lineHeight: 18, marginTop: 10 },
  autopilotRuleCard: { borderWidth: 1, borderColor: "#36547B", backgroundColor: C.blueSoft, borderRadius: 16, padding: 14, marginBottom: 10, gap: 10 },
  autopilotRuleText: { color: C.ink, fontSize: 14, lineHeight: 20, fontWeight: "800" },
  autopilotRuleMeta: { color: C.muted, fontSize: 11, marginTop: 6, fontWeight: "700" },
  proactiveFieldLabel: { color: C.muted, fontSize: 11, fontWeight: "800", letterSpacing: 0.3, marginTop: 10, marginBottom: 5 },
  proactiveCompactInput: { borderWidth: 1, borderColor: C.border, borderRadius: 12, backgroundColor: C.card, color: C.ink, fontSize: 15, paddingHorizontal: 12, paddingVertical: 10, marginBottom: 4 },
  proactiveChoiceRow: { gap: 8, marginTop: 4 },
  releaseCheckRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, borderWidth: 1, borderColor: C.border, backgroundColor: C.card, borderRadius: 14, paddingHorizontal: 14, paddingVertical: 12, marginBottom: 8 },
  releaseCheckLabel: { flex: 1, color: C.ink, fontSize: 14, fontWeight: "800" },
  productionReadinessDetail: { color: C.muted, fontSize: 12, lineHeight: 17, marginTop: 4 },
  nav: {
    height: 72,
    flexDirection: "row",
    backgroundColor: C.card,
    borderTopWidth: 1,
    borderTopColor: C.border,
    alignItems: "center",
    justifyContent: "space-around",
    paddingBottom: 5,
  },
  navItem: { alignItems: "center", justifyContent: "center", minWidth: 68 },
  navDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: "transparent", marginBottom: 5 },
  navDotActive: { backgroundColor: C.blue },
  navText: { color: C.muted, fontSize: 13, fontWeight: "700" },
  navTextActive: { color: C.blueText, fontWeight: "900" },
});

